// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {settings} from '../models';

export function DeleteAllEmails():Promise<void>;

export function DeleteEmail(arg1:string):Promise<void>;

export function GetEmail(arg1:string):Promise<models.Email>;

export function GetEmailCount():Promise<number>;

export function GetPort():Promise<string>;

export function GetRawSource(arg1:string):Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function ListEmails(arg1:string,arg2:number,arg3:number):Promise<Array<models.EmailSummary>>;

export function MarkAsRead(arg1:string):Promise<void>;

export function SaveAttachment(arg1:string):Promise<string>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;
