// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAllEmails() {
  return window['go']['main']['App']['DeleteAllEmails']();
}

export function DeleteEmail(arg1) {
  return window['go']['main']['App']['DeleteEmail'](arg1);
}

export function GetEmail(arg1) {
  return window['go']['main']['App']['GetEmail'](arg1);
}

export function GetEmailCount() {
  return window['go']['main']['App']['GetEmailCount']();
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function GetRawSource(arg1) {
  return window['go']['main']['App']['GetRawSource'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListEmails(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListEmails'](arg1, arg2, arg3);
}

export function MarkAsRead(arg1) {
  return window['go']['main']['App']['MarkAsRead'](arg1);
}

export function SaveAttachment(arg1) {
  return window['go']['main']['App']['SaveAttachment'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
